enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
included-patches = "'Hide ads' 'Video ads' 'Copy video URL' 'Disable resuming Shorts on startup' 'Bypass image region restrictions' 'Remove background playback restrictions' 'Check watch history domain name resolution' 'Spoof video streams' 'Force original audio' 'Remember video quality' 'Restore old video quality menu'"
exclusive-patches = true
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
